import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class HelpService {
  private helpContents = new Map<string, string[]>();

  constructor() {
    // Initialize help contents for different screens
    this.helpContents.set('add-vehicle', [
      'This page is for administrators.',
      '',
      'You have the privilege of adding a new vehicle to the Jones and Wagener pool vehicles.',
      
      'You need to provide details like Name, Description, Date Acquired, etc.',
      'The vehicle status will automatically be set to "Available". ',
      'Ensure all required fields are filled before submitting the form.'
    ]);

    this.helpContents.set('add-booking', [
      'This page is for registered users.',
      'You have access to make a booking for a vehicle for business purposes.',
      'You need to provide information by selecting a vehicle from the dropdown list and stating whether its for a project or an event.',
      'Start Date can only be the current date or a later date',
      'Ensure all required fields are filled before submitting the form.'
    ]);

    this.helpContents.set('edit-vehicle/:id', [
      'This page is for administrators.',
      'You have access to updating the existing vehicle details on the screen',
      'If you need to cancel, please click on the grey Cancel button at the bottom of the screen',
      'Ensure all required fields are filled before submitting the form.'
    ]);

    this.helpContents.set('booking-history', [
      'This page allows you to view your booking history at Jones and Wagener Pool Vehicles.',
      'Here, you can complete your pre-checklist by clicking on the green button, that ensures that the vehicle is in good condition before use',
      
    ]);

    this.helpContents.set('get-trip', [
     'This page allows registered users to view their entire trip history.',
     'Users can edit, delete and post refuel details by clicking on the applicable buttons. ',
     'Please note: The Refuel button is only enabled when the trip is still active. When the Travel End Date has passed, the button is disabled'
    ]);

    this.helpContents.set('trip', [
      'This page is for administrators.',
      'You have access to generate various administrative reports including viewing all trips by other administrators and drivers.',
      'Here, you can download a XML file of all the trips by clicking on the "Download All Trips as XML" button '
    ]);

    this.helpContents.set('pool-vehicle', [
     'This page is for all registered users.',
      'You can view the available vehicles in the system by clicking on the "View Vehicles" button which will display a full attributed list of the vehicle at hand ',
    ]);

    this.helpContents.set('driver', [
      'This page is for registered drivers.',
      'You have the privilege of updating your details as well as removing yourself from the system.',
    ]);
  

    this.helpContents.set('service', [
      'This page is for administrators.',
      'You have access to generate various administrative reports here.',
    ]);

    this.helpContents.set('booking-list', [
      'This page is for registered users.',
      'Administrators are able to see each and every booking made on the system.',
      'Drivers are only able to view their own booking list'
    ]);

    this.helpContents.set('app-report', [
      'This page is for administrators.',
      'You have access to generate various administrative reports here.',
      'Reports are generated by you clicking on the "Generate ... Report" button'
    ]);

    this.helpContents.set('view-post-check', [
      'This page is for administrators.',
      'You have the privilege of viewing all submitted post-checklists',
      'As the administrators, you are able to see any issues reported through the use of media by scrolling to the right of the screen and clicking on each picture and downloading it. '
    ]);

    // Add more help contents for other screens
  }

  getHelpContents(screen: string): string[] {
    return this.helpContents.get(screen) || [];
  }

  searchHelp(screen: string, query: string): { content: string, highlighted: string }[] {
    const results: { content: string, highlighted: string }[] = [];
    const helpContents = this.getHelpContents(screen);
    
    if (query.trim()) {
      helpContents.forEach(content => {
        if (content.toLowerCase().includes(query.toLowerCase())) {
          const highlighted = this.highlightSearchTerm(content, query);
          results.push({ content, highlighted });
        }
      });
    }
    
    return results;
  }

  private highlightSearchTerm(content: string, query: string): string {
    const regex = new RegExp(`(${query})`, 'gi');
    return content.replace(regex, '<span class="highlight">$1</span>');
  }
}
